/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes;

import Proyecto.FormularioRegistro.Cliente;
import Proyecto.FormularioRegistro.Frm_Registros;
import Proyecto.Frm_Turnos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mjiad
 */
public class Frm_Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Reportes
     */
    DefaultTableModel model = new DefaultTableModel();
    ArrayList<Cliente> lista;
    String[] ListaCombo = {"Numero de clientes atendidos", "Tiempo de espera por cliente", "Cantidad de turnos atendidos por empleado", "Clientes que abandonaron"};

    String[] ListaAtendidosDia = {"Tipo identficacion", "Numero de identificacion", "Fecha del turno"};
    String[] ListaNoAtendidos = {"Tipo de identificacion", "Numero identificacion"};
    Frm_Registros registros;
    Frm_Turnos turnos;

    public Frm_Reportes() {
        initComponents();
        registros = turnos.getRegistros();
        lista = registros.getListaDocumentos();
        turnos = turnos.getInstance();

        setLocationRelativeTo(null);
        ComoBobox_Reportes.removeAllItems();
        ComoBobox_Reportes.addItem("Seleccione...");
        for (int i = 0; i < ListaCombo.length; i++) {
            ComoBobox_Reportes.addItem(ListaCombo[i]);
        }
    }

    public void RellenarTablos(int Indice) {
        
        for (Cliente cliente : lista) {
            if (cliente.getFechaTurno() != null && Indice == 1) {
                model.setColumnIdentifiers(ListaAtendidosDia);
                model.addRow(new Object[]{
                    cliente.getTipoIdendificacion(),
                    cliente.getNumeroIdentificacion(),
                    cliente.getFechaTurno(),});
            } else if (Indice == 4 && cliente.getFechaTurno() == null) {
                model.setColumnIdentifiers(ListaNoAtendidos);
                model.setRowCount(0);
                model.addRow(new Object[]{
                    cliente.getTipoIdendificacion(),
                    cliente.getNumeroIdentificacion(),});
            }
        }
        Tabla_Reportes.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComoBobox_Reportes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Reportes = new javax.swing.JTable();
        Btn_Reportes = new javax.swing.JButton();
        Btn_ExportarExcel = new javax.swing.JButton();
        Btn_Dia = new javax.swing.JButton();
        Btn_Semana = new javax.swing.JButton();
        Btn_Mes = new javax.swing.JButton();
        Lb_ClientesDSM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reportes");

        jLabel1.setText("Reportes");

        ComoBobox_Reportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComoBobox_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComoBobox_ReportesActionPerformed(evt);
            }
        });

        Tabla_Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Reportes);

        Btn_Reportes.setText("Mostrar Reporte");
        Btn_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReportesActionPerformed(evt);
            }
        });

        Btn_ExportarExcel.setText("Exportar Reporte (Excel)");

        Btn_Dia.setText("Dia");

        Btn_Semana.setText("Semana");

        Btn_Mes.setText("Mes");

        Lb_ClientesDSM.setText("Clientes atendidos por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ComoBobox_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Reportes)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_ExportarExcel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Dia)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Semana)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Mes))
                    .addComponent(Lb_ClientesDSM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComoBobox_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Reportes)
                    .addComponent(Btn_ExportarExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(Lb_ClientesDSM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Dia)
                    .addComponent(Btn_Semana)
                    .addComponent(Btn_Mes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComoBobox_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComoBobox_ReportesActionPerformed
        // TODO add your handling code here:
        /*No there nothin here*/
    }//GEN-LAST:event_ComoBobox_ReportesActionPerformed

    private void Btn_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReportesActionPerformed
        // TODO add your handling code here:
        int indiceCombo = ComoBobox_Reportes.getSelectedIndex();
        String seleccion = (String) ComoBobox_Reportes.getSelectedItem();
        if (seleccion != null) {
            RellenarTablos(indiceCombo);
        } else {
            BotonesDesactivados();
        }
    }//GEN-LAST:event_Btn_ReportesActionPerformed

    public void BotonesActivos() {
        Btn_Dia.setEnabled(true);
        Btn_Semana.setEnabled(true);
        Btn_Mes.setEnabled(true);

        Btn_Dia.setVisible(true);
        Btn_Semana.setVisible(true);
        Btn_Mes.setVisible(true);
        Lb_ClientesDSM.setVisible(true);
    }

    public void BotonesDesactivados() {
        Btn_Dia.setEnabled(false);
        Btn_Semana.setEnabled(false);
        Btn_Mes.setEnabled(false);

        Btn_Dia.setVisible(false);
        Btn_Semana.setVisible(false);
        Btn_Mes.setVisible(false);
        Lb_ClientesDSM.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Dia;
    private javax.swing.JButton Btn_ExportarExcel;
    private javax.swing.JButton Btn_Mes;
    private javax.swing.JButton Btn_Reportes;
    private javax.swing.JButton Btn_Semana;
    private javax.swing.JComboBox<String> ComoBobox_Reportes;
    private javax.swing.JLabel Lb_ClientesDSM;
    private javax.swing.JTable Tabla_Reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
